// AUTO-GENERATED by scripts/gen-slot-registry.ts — DO NOT EDIT
import type { ReactNode } from 'react';
import { dashboardSlots as bannerSlots } from '@/features/banner/dashboard-slots';

export type SlotName = 'dashboard-top' | 'global-popup';
export type SlotEntry = () => ReactNode;

export const SLOT_REGISTRY: Record<SlotName, SlotEntry[]> = {
  'dashboard-top': [bannerSlots['dashboard-top']].filter(Boolean) as SlotEntry[],
  'global-popup': [bannerSlots['global-popup']].filter(Boolean) as SlotEntry[],
};
