/**
 * gen-slot-registry — features/*\/dashboard-slots.tsx 를 글롭해 슬롯 레지스트리를 생성한다.
 *
 * 사용: tsx scripts/gen-slot-registry.ts
 *
 * 설치된 모듈만 `features/<id>/dashboard-slots.tsx`를 가지므로, 이 파일들을
 * 스캔해 import하는 generated 파일을 만들면 모듈 설치 여부가 자동 반영된다.
 * 모듈이 0개여도 유효한 빈 레지스트리를 생성한다.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

const ROOT = process.cwd();
const FEATURES_DIR = 'apps/core-frontend/src/features';
const OUT = 'apps/core-frontend/src/shared/components/slot-registry.generated.ts';
const SLOT_NAMES = ['dashboard-top', 'global-popup'] as const;

/** 'user-profile' → 'userProfileSlots' 처럼 하이픈 id를 camelCase 변수명으로 변환 */
function toVarName(id: string): string {
  return id.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) + 'Slots';
}

function findSlotModules(): { id: string; varName: string; importPath: string }[] {
  const base = path.join(ROOT, FEATURES_DIR);
  if (!fs.existsSync(base)) return [];
  const found: { id: string; varName: string; importPath: string }[] = [];
  for (const id of fs.readdirSync(base)) {
    const file = path.join(base, id, 'dashboard-slots.tsx');
    if (fs.existsSync(file)) {
      found.push({ id, varName: toVarName(id), importPath: `@/features/${id}/dashboard-slots` });
    }
  }
  return found.sort((a, b) => a.id.localeCompare(b.id));
}

function generate(): string {
  const mods = findSlotModules();
  const imports = mods
    .map((m) => `import { dashboardSlots as ${m.varName} } from '${m.importPath}';`)
    .join('\n');
  const importBlock = imports ? `${imports}\n` : '';
  const slotLines = SLOT_NAMES.map((slot) => {
    const items = mods.map((m) => `${m.varName}['${slot}']`).join(', ');
    return `  '${slot}': [${items}].filter(Boolean) as SlotEntry[],`;
  }).join('\n');

  return `// AUTO-GENERATED by scripts/gen-slot-registry.ts — DO NOT EDIT
import type { ReactNode } from 'react';
${importBlock}
export type SlotName = ${SLOT_NAMES.map((s) => `'${s}'`).join(' | ')};
export type SlotEntry = () => ReactNode;

export const SLOT_REGISTRY: Record<SlotName, SlotEntry[]> = {
${slotLines}
};
`;
}

const mods = findSlotModules();
if (mods.length === 0) {
  // eslint-disable-next-line no-console
  console.warn('[slots] dashboard-slots.tsx를 가진 모듈이 없습니다 — 빈 레지스트리 생성');
}
fs.writeFileSync(path.join(ROOT, OUT), generate());
// eslint-disable-next-line no-console
console.log(`✅ slot-registry 생성: ${mods.length}개 모듈${mods.length ? ` (${mods.map((m) => m.id).join(', ')})` : ''}`);
